version: '3.9'

services:
  backendwithfrontend:
    container_name: backendwithfrontend
    build:
      context: .
      dockerfile: Dockerfile-local
    ports:
      - 6200:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres_container:5432/cloudformation
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
    networks:
      - local-dev-net
    command: java -jar app.jar

networks:
  local-dev-net:
    driver: bridge

volumes:
  postgres:
