version: '3.9'

services:
  backendwithfrontend:
    container_name: backendwithfrontend
    build:
      context: .
      dockerfile: Dockerfile-local
    ports:
      - 6200:8080
    environment:
      - COGNITO_DOMAIN=${COGNITO_DOMAIN}
      - CLIENT_ID=${CLIENT_ID}
      - CLIENT_SECRET=${CLIENT_SECRET}
      - COGNITO_USERPOOL_ID=${COGNITO_USERPOOL_ID}
    networks:
      - cognito-try-net
    command: java -jar app.jar

networks:
  cognito-try-net:
    driver: bridge

