version: '3.9'

services:
  backendwithfrontend:
    container_name: backendwithfrontend
    build:
      context: .
      dockerfile: Dockerfile-local
    ports:
      - 6200:8080
    environment:
      - COGNITO_DOMAIN=https://ogata-cog.auth.ap-northeast-1.amazoncognito.com
      - CLIENT_ID=j6r038j8e9m443ljqa6q6b0rn
      - CLIENT_SECRET=rda48ncgfjks4soh4r98helq4m888sggjcq0083ae7f8k3utkde
      - COGNITO_USERPOOL_ID=ap-northeast-1_zgWAK6odx
    networks:
      - cognito-try-net
    command: java -jar app.jar

networks:
  cognito-try-net:
    driver: bridge

