AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  cloudfront-lambda-register

  Sample SAM Template for cloudfront-lambda-register

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
  Api:
    Cors:
      AllowMethods: "'*'"
      AllowHeaders: "'*'"
      AllowOrigin: "'*'"

Resources:
  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Cors:
        AllowMethods: "'GET,POST,PUT,DELETE,OPTIONS'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
        AllowOrigin: "'*'"
      Auth:
        ResourcePolicy:
          CustomStatements:
            - Effect: Allow
              Principal: '*'
              Action: execute-api:Invoke
              Resource: execute-api:/*
              Condition:
                IpAddress:
                  aws:SourceIp: '13.114.22.14/32'
            - Effect: Deny
              Principal: '*'
              Action: execute-api:Invoke
              Resource: execute-api:/*
              Condition:
                NotIpAddress:
                  aws:SourceIp: '13.114.22.14/32'

  LambdaUserResister:
    Type: AWS::Serverless::Function
    Properties:
      Environment:
        Variables:
          USER_POOL_ID: ap-northeast-1_zgWAK6odx
      CodeUri: lambdafunction/
      Handler: userResister.lambdaHandler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      Role:
        Fn::Sub: 'arn:aws:iam::${AWS::AccountId}:role/ogata-lambdaExecutionRole'
      Events:
        userResister:
          Type: Api
          Properties:
            Path: /api/users
            Method: post
            RestApiId: !Ref ApiGatewayApi
      Timeout: 15
      MemorySize: 256
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: 'es2020'
        Sourcemap: true
        EntryPoints:
          - controller/userResister.ts

  LambdaUserAllGet:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambdafunction/
      Handler: userAllGet.lambdaHandler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      Role:
        Fn::Sub: 'arn:aws:iam::${AWS::AccountId}:role/ogata-lambdaExecutionRole'
      Events:
        userAllGet:
          Type: Api
          Properties:
            Path: /api/users
            Method: get
            RestApiId: !Ref ApiGatewayApi
      Timeout: 15
      MemorySize: 256
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: 'es2020'
        Sourcemap: true
        EntryPoints:
          - controller/userAllGet.ts

  LambdaUserDelete:
    Type: AWS::Serverless::Function
    Properties:
      Environment:
        Variables:
          USER_POOL_ID: ap-northeast-1_zgWAK6odx
      CodeUri: lambdafunction/
      Handler: userDelete.lambdaHandler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      Role:
        Fn::Sub: 'arn:aws:iam::${AWS::AccountId}:role/ogata-lambdaExecutionRole'
      Events:
        userAllGet:
          Type: Api
          Properties:
            Path: /api/users/{id}
            Method: delete
            RestApiId: !Ref ApiGatewayApi
      Timeout: 15
      MemorySize: 256
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: 'es2020'
        Sourcemap: true
        EntryPoints:
          - controller/userDelete.ts
#Outputs:
#  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
#  # Find out more about other implicit resources you can reference within SAM
#  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
#  HelloWorldApi:
#    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
#    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
#  LambdaUserResister:
#    Description: "Hello World Lambda Function ARN"
#    Value: !GetAtt HelloWorldFunction.Arn
#  HelloWorldFunctionIamRole:
#    Description: "Implicit IAM Role created for Hello World function"
#    Value: !GetAtt HelloWorldFunctionRole.Arn
