spring:
  security:
    oauth2:
      client:
        registration:
          cognito:
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
            scope: openid
            redirect-uri: "{baseUrl}/login/oauth2/code/cognito"
            authorization-grant-type: authorization_code
        provider:
          cognito:
            issuer-uri: https://cognito-idp.ap-northeast-1.amazonaws.com/ap-northeast-1_15KmrsaZP
            authorization-uri: ${COGNITO_DOMAIN}/oauth2/authorize

environments:
  after-auth-redirect-url: "http://localhost:5173/"
  login-error-redirect-url: "http://localhost:5173/"